-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    ["mail"] = {
    },
    ["date"] = {
        ["date_format"] = "%a %Y-%m-%d %H:%M",
    },
    ["linuxbatt"] = {
    },
    ["tempinfo"] = {
    },
    ["load"] = {
    },
}

