-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    [1] = "run:firefox",
    [2] = "framename:main",
    [3] = "menu.mainmenu:session/exit",
    [4] = "menu.mainmenu:session/restart",
    [5] = "yesno:y",
}

