-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    [0] = {
        ["name"] = "WScreen",
        ["type"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["geom"] = {
                    ["w"] = 1366,
                    ["h"] = 768,
                    ["y"] = 0,
                    ["x"] = 0,
                },
                ["level"] = 0,
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["w"] = 1366,
                            ["h"] = 768,
                            ["y"] = 0,
                            ["x"] = 0,
                        },
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                        ["split_tree"] = {
                            ["dir"] = "horizontal",
                            ["tl"] = {
                                ["dir"] = "vertical",
                                ["tl"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["managed"] = {
                                            [1] = {
                                                ["geom"] = {
                                                    ["w"] = 681,
                                                    ["h"] = 731,
                                                    ["y"] = 18,
                                                    ["x"] = 1,
                                                },
                                                ["managed"] = {
                                                    [1] = {
                                                        ["geom"] = {
                                                            ["w"] = 680,
                                                            ["h"] = 728,
                                                            ["y"] = 1,
                                                            ["x"] = 0,
                                                        },
                                                        ["type"] = "WClientWin",
                                                        ["bottom"] = true,
                                                        ["level"] = 0,
                                                        ["checkcode"] = 1,
                                                        ["sizepolicy"] = "full",
                                                        ["windowid"] = 10485766,
                                                    },
                                                },
                                                ["level"] = 0,
                                                ["switchto"] = true,
                                                ["name"] = "WGroupCW",
                                                ["sizepolicy"] = "full",
                                                ["type"] = "WGroupCW",
                                            },
                                        },
                                        ["name"] = "WFrame",
                                        ["type"] = "WFrame",
                                        ["mode"] = 1,
                                    },
                                },
                                ["br"] = {
                                    ["type"] = "WSplitST",
                                },
                                ["tls"] = 750,
                                ["brs"] = 18,
                                ["type"] = "WSplitSplit",
                            },
                            ["br"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["managed"] = {
                                        [1] = {
                                            ["geom"] = {
                                                ["w"] = 681,
                                                ["h"] = 749,
                                                ["y"] = 18,
                                                ["x"] = 1,
                                            },
                                            ["managed"] = {
                                                [1] = {
                                                    ["geom"] = {
                                                        ["w"] = 681,
                                                        ["h"] = 749,
                                                        ["y"] = 0,
                                                        ["x"] = 0,
                                                    },
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["level"] = 0,
                                                    ["checkcode"] = 2,
                                                    ["sizepolicy"] = "full",
                                                    ["windowid"] = 14680067,
                                                },
                                            },
                                            ["hidden"] = true,
                                            ["level"] = 0,
                                            ["name"] = "WGroupCW<1>",
                                            ["sizepolicy"] = "full",
                                            ["type"] = "WGroupCW",
                                        },
                                        [2] = {
                                            ["geom"] = {
                                                ["w"] = 681,
                                                ["h"] = 749,
                                                ["y"] = 18,
                                                ["x"] = 1,
                                            },
                                            ["managed"] = {
                                                [1] = {
                                                    ["geom"] = {
                                                        ["w"] = 680,
                                                        ["h"] = 746,
                                                        ["y"] = 1,
                                                        ["x"] = 0,
                                                    },
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["level"] = 0,
                                                    ["checkcode"] = 3,
                                                    ["sizepolicy"] = "full",
                                                    ["windowid"] = 10504424,
                                                },
                                            },
                                            ["level"] = 0,
                                            ["switchto"] = true,
                                            ["name"] = "WGroupCW<2>",
                                            ["sizepolicy"] = "full",
                                            ["type"] = "WGroupCW",
                                        },
                                    },
                                    ["name"] = "Tiling Frame",
                                    ["type"] = "WFrame",
                                    ["mode"] = 1,
                                },
                            },
                            ["tls"] = 683,
                            ["brs"] = 683,
                            ["type"] = "WSplitSplit",
                        },
                        ["name"] = "WTiling",
                        ["level"] = 0,
                        ["bottom"] = true,
                    },
                },
                ["sizepolicy"] = "full",
                ["switchto"] = true,
                ["name"] = "main",
                ["initial_outputs"] = {
                    [1] = "eDP-1-1",
                },
                ["type"] = "WGroupWS",
            },
            [2] = {
                ["sizepolicy"] = "full",
                ["level"] = 1,
                ["name"] = "*scratchws*",
                ["geom"] = {
                    ["w"] = 1366,
                    ["h"] = 768,
                    ["y"] = 0,
                    ["x"] = 0,
                },
                ["type"] = "WGroupWS",
                ["hidden"] = true,
                ["unnumbered"] = true,
                ["initial_outputs"] = {
                },
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["w"] = 640,
                            ["h"] = 480,
                            ["y"] = 144,
                            ["x"] = 363,
                        },
                        ["managed"] = {
                        },
                        ["type"] = "WFrame",
                        ["mode"] = 0,
                        ["level"] = 1024,
                        ["name"] = "*scratchpad*",
                        ["sizepolicy"] = "free_glue",
                        ["bottom"] = true,
                    },
                },
            },
        },
    },
}

