-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    ["tempinfo"] = {
    },
    ["load"] = {
    },
    ["date"] = {
        ["date_format"] = "%a %Y-%m-%d %H:%M",
    },
    ["linuxbatt"] = {
        ["bat"] = {
            [1] = 1,
            [2] = 0,
        },
        ["critical_threshold"] = 10,
        ["important_threshold"] = 30,
    },
    ["uptime"] = {
    },
    ["mocmon"] = {
        ["do_monitors"] = false,
        ["user_format"] = "%songtitle% - %artist%",
        ["interval"] = 2000,
        ["not_running"] = "stopped",
    },
    ["mail"] = {
    },
    ["df"] = {
        ["update_interval"] = 5000,
        ["fslist"] = {
            [1] = "/",
        },
        ["template"] = "%mpoint: %used/%size (%usedp)",
    },
    ["meminfo"] = {
        ["update_interval"] = 10000,
    },
    ["itime"] = {
    },
    ["workspace"] = {
    },
}

