-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    [0] = {
        ["type"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["geom"] = {
                    ["x"] = 0,
                    ["w"] = 1440,
                    ["h"] = 900,
                    ["y"] = 0,
                },
                ["initial_outputs"] = {
                    [1] = "LVDS-1",
                },
                ["level"] = 0,
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["geom"] = {
                            ["x"] = 0,
                            ["w"] = 1440,
                            ["h"] = 900,
                            ["y"] = 0,
                        },
                        ["split_tree"] = {
                            ["tl"] = {
                                ["tl"] = {
                                    ["type"] = "WSplitRegion",
                                    ["regparams"] = {
                                        ["type"] = "WFrame",
                                        ["managed"] = {
                                            [1] = {
                                                ["geom"] = {
                                                    ["x"] = 1,
                                                    ["w"] = 799,
                                                    ["h"] = 866,
                                                    ["y"] = 18,
                                                },
                                                ["level"] = 0,
                                                ["sizepolicy"] = "full",
                                                ["type"] = "WGroupCW",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["checkcode"] = 1,
                                                        ["windowid"] = 25165840,
                                                        ["bottom"] = true,
                                                        ["type"] = "WClientWin",
                                                        ["sizepolicy"] = "full",
                                                        ["level"] = 1,
                                                        ["geom"] = {
                                                            ["x"] = 0,
                                                            ["w"] = 799,
                                                            ["h"] = 866,
                                                            ["y"] = 0,
                                                        },
                                                    },
                                                },
                                                ["name"] = "WGroupCW<1>",
                                                ["switchto"] = true,
                                            },
                                        },
                                        ["name"] = "Tiling Frame<1>",
                                        ["mode"] = 1,
                                    },
                                },
                                ["tls"] = 801,
                                ["dir"] = "horizontal",
                                ["type"] = "WSplitSplit",
                                ["brs"] = 639,
                                ["br"] = {
                                    ["tl"] = {
                                        ["type"] = "WSplitRegion",
                                        ["regparams"] = {
                                            ["type"] = "WFrame",
                                            ["managed"] = {
                                                [1] = {
                                                    ["geom"] = {
                                                        ["x"] = 1,
                                                        ["w"] = 637,
                                                        ["h"] = 424,
                                                        ["y"] = 18,
                                                    },
                                                    ["level"] = 0,
                                                    ["sizepolicy"] = "full",
                                                    ["type"] = "WGroupCW",
                                                    ["managed"] = {
                                                        [1] = {
                                                            ["checkcode"] = 2,
                                                            ["windowid"] = 12582927,
                                                            ["bottom"] = true,
                                                            ["type"] = "WClientWin",
                                                            ["sizepolicy"] = "full",
                                                            ["level"] = 1,
                                                            ["geom"] = {
                                                                ["x"] = 0,
                                                                ["w"] = 637,
                                                                ["h"] = 420,
                                                                ["y"] = 2,
                                                            },
                                                        },
                                                    },
                                                    ["name"] = "WGroupCW",
                                                    ["switchto"] = true,
                                                },
                                            },
                                            ["name"] = "Tiling Frame",
                                            ["mode"] = 1,
                                        },
                                    },
                                    ["tls"] = 443,
                                    ["dir"] = "vertical",
                                    ["type"] = "WSplitSplit",
                                    ["brs"] = 442,
                                    ["br"] = {
                                        ["type"] = "WSplitRegion",
                                        ["regparams"] = {
                                            ["type"] = "WFrame",
                                            ["managed"] = {
                                                [1] = {
                                                    ["geom"] = {
                                                        ["x"] = 1,
                                                        ["w"] = 637,
                                                        ["h"] = 423,
                                                        ["y"] = 18,
                                                    },
                                                    ["level"] = 0,
                                                    ["sizepolicy"] = "full",
                                                    ["type"] = "WGroupCW",
                                                    ["managed"] = {
                                                        [1] = {
                                                            ["checkcode"] = 3,
                                                            ["windowid"] = 18874383,
                                                            ["bottom"] = true,
                                                            ["type"] = "WClientWin",
                                                            ["sizepolicy"] = "full",
                                                            ["level"] = 1,
                                                            ["geom"] = {
                                                                ["x"] = 0,
                                                                ["w"] = 637,
                                                                ["h"] = 420,
                                                                ["y"] = 1,
                                                            },
                                                        },
                                                    },
                                                    ["name"] = "WGroupCW<2>",
                                                    ["switchto"] = true,
                                                },
                                            },
                                            ["name"] = "Tiling Frame<2>",
                                            ["mode"] = 1,
                                        },
                                    },
                                },
                            },
                            ["tls"] = 885,
                            ["dir"] = "vertical",
                            ["type"] = "WSplitSplit",
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                        },
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling",
                        ["level"] = 0,
                    },
                },
                ["name"] = "WGroupWS",
                ["switchto"] = true,
            },
            [2] = {
                ["level"] = 0,
                ["initial_outputs"] = {
                },
                ["geom"] = {
                    ["x"] = 0,
                    ["w"] = 1440,
                    ["h"] = 900,
                    ["y"] = 0,
                },
                ["hidden"] = true,
                ["type"] = "WGroupWS",
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["geom"] = {
                            ["x"] = 0,
                            ["w"] = 1440,
                            ["h"] = 900,
                            ["y"] = 0,
                        },
                        ["split_tree"] = {
                            ["tl"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["type"] = "WFrame",
                                    ["managed"] = {
                                    },
                                    ["name"] = "WFrame<2>",
                                    ["mode"] = 1,
                                },
                            },
                            ["tls"] = 720,
                            ["dir"] = "horizontal",
                            ["type"] = "WSplitSplit",
                            ["brs"] = 720,
                            ["br"] = {
                                ["type"] = "WSplitRegion",
                                ["regparams"] = {
                                    ["type"] = "WFrame",
                                    ["managed"] = {
                                    },
                                    ["name"] = "WFrame<3>",
                                    ["mode"] = 1,
                                },
                            },
                        },
                        ["type"] = "WTiling",
                        ["sizepolicy"] = "full",
                        ["name"] = "WTiling<1>",
                        ["level"] = 0,
                    },
                },
                ["name"] = "WGroupWS<1>",
                ["sizepolicy"] = "full",
            },
            [3] = {
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["level"] = 1,
                ["unnumbered"] = true,
                ["hidden"] = true,
                ["pseudomodal"] = true,
                ["geom"] = {
                    ["x"] = 0,
                    ["w"] = 1440,
                    ["h"] = 900,
                    ["y"] = 0,
                },
                ["name"] = "*scratchws*",
                ["managed"] = {
                    [1] = {
                        ["bottom"] = true,
                        ["geom"] = {
                            ["x"] = 400,
                            ["w"] = 639,
                            ["h"] = 479,
                            ["y"] = 210,
                        },
                        ["level"] = 1025,
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                        ["managed"] = {
                            [1] = {
                                ["geom"] = {
                                    ["x"] = 1,
                                    ["w"] = 637,
                                    ["h"] = 459,
                                    ["y"] = 18,
                                },
                                ["level"] = 0,
                                ["sizepolicy"] = "full",
                                ["type"] = "WGroupCW",
                                ["managed"] = {
                                    [1] = {
                                        ["checkcode"] = 4,
                                        ["windowid"] = 27262991,
                                        ["bottom"] = true,
                                        ["type"] = "WClientWin",
                                        ["sizepolicy"] = "full",
                                        ["level"] = 1,
                                        ["geom"] = {
                                            ["x"] = 0,
                                            ["w"] = 637,
                                            ["h"] = 459,
                                            ["y"] = 0,
                                        },
                                    },
                                },
                                ["name"] = "WGroupCW<3>",
                                ["switchto"] = true,
                            },
                        },
                        ["name"] = "*scratchpad*",
                        ["mode"] = 0,
                    },
                },
            },
        },
        ["name"] = "WScreen",
    },
}

