#!/usr/bin/perl

use strict;

my $root = $ARGV[0];
my $delay = $ARGV[1];
my $reactualize = $ARGV[2];
my @filelist;
my $program = "Esetroot -fit";

#
# Checks whether a file is an image, based on the extension
# Not the smartest, but the fastest and easiest way to do it.
#
sub file_is_image
{
	my $f = shift;
	my @extensions = ("png", "jpg", "jpeg", "gif", "bmp", "tiff", "xpm", "tif");
	$f =~ /\.([^\.]+)$/;
	my $ext = $1;
	for my $e (@extensions) {
		return 1 if lc($ext) eq $e;
	}
	return 0;
}

sub get_file_list
{
	my $dir = shift;
	my @flist = glob("$dir/*");
	foreach my $f (@flist) {
		if (-d $f) {
			&get_file_list ($f);
		}
		else {
			$f =~ s/(\s)/\\$1/g;
			if (&file_is_image($f)) {
				push @filelist, $f;
			}
		}
	}
}

sub display_file
{
	my $f = shift;
	
	return(-1) unless (-f $f);
	return(-1) if system("$program $f");
	return(-1) if system("xrefresh");
}

if ($delay eq "") {
	$delay = 120;
}
print("Setting delay to $delay seconds\n");

if ($reactualize eq "") {
	$reactualize = 30;
}
else {
	$reactualize = $reactualize*60/$delay;
}

print("Reactualizing every " . $delay*$reactualize/60 . " minutes\n");

my $t = $reactualize;
while(1) {
	if ($t == $reactualize) {
		@filelist = [];
		$t = 0;
		&get_file_list($root);
		print("Read file list in $root. $#filelist image files found.\n");
	}
	else {
		$t++;
	}

	my $f;
	do {
		$f = $filelist[rand @filelist];
	}
	while (&display_file($f)); 
	sleep($delay);
}
