-- This file has been generated by Ion. Do not edit.
return {
    ["df"] = {
        ["template"] = "%mpoint: %used/%size",
        ["update_interval"] = 5000,
    },
    ["meminfo"] = {
    },
    ["date"] = {
        ["date_format"] = "%a %Y-%m-%d %H:%M",
    },
    ["mail"] = {
    },
    ["load"] = {
    },
    ["linuxbatt"] = {
        ["important_threshold"] = 30,
        ["critical_threshold"] = 10,
        ["bat"] = {
            [1] = 1,
            [2] = 0,
        },
    },
}

