-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    [1] = "windowname:seb@Proserpine: ~",
    [2] = "workspacelayout:",
    [3] = "workspacename:",
    [4] = "run:xterm",
    [5] = "menu.mainmenu:session/restart",
    [6] = "menu.mainmenu:",
    [7] = "run:firefox",
    [8] = "run:keepass2",
    [9] = "run:musescore",
    [10] = "yesno:y",
    [11] = "menu.mainmenu:sessions/redémarrer",
}

