-- This file has been generated by /usr/bin/notion. Do not edit.
return {
    [1] = "run:xterm",
    [2] = "menu.mainmenu:session/restart",
    [3] = "menu.mainmenu:",
    [4] = "run:firefox",
    [5] = "run:keepass2",
    [6] = "run:musescore",
    [7] = "yesno:y",
    [8] = "menu.mainmenu:sessions/redémarrer",
}

